export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const FETCH_CONTACTS_FULFILLED = "FETCH_CONTACTS_FULFILLED";

export const FETCH_CONTACT = "FETCH_CONTACT";
export const FETCH_CONTACT_PENDING = "FETCH_CONTACT_PENDING";
export const FETCH_CONTACT_FULFILLED = "FETCH_CONTACT_FULFILLED";

export const NEW_CONTACT = "NEW_CONTACT";

export const SAVE_CONTACT = "SAVE_CONTACT";
export const SAVE_CONTACT_PENDING = "SAVE_CONTACT_PENDING";
export const SAVE_CONTACT_FULFILLED = "SAVE_CONTACT_FULFILLED";
export const SAVE_CONTACT_REJECTED = "SAVE_CONTACT_REJECTED";

export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_PENDING = "UPDATE_CONTACT_PENDING";
export const UPDATE_CONTACT_FULFILLED = "UPDATE_CONTACT_FULFILLED";
export const UPDATE_CONTACT_REJECTED = "UPDATE_CONTACT_REJECTED";

export const DELETE_CONTACT = "DELETE_CONTACT";
export const DELETE_CONTACT_FULFILLED = "DELETE_CONTACT_FULFILLED";

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";